exclude_paths:
  - vendor/**/*
engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,lib"
      standard: "WordPress"
      ignore_warnings: true
      encoding: utf-8
ratings:
  paths:
  - "**.php"
  
